adra/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt import views as jwt_views

from . import views
from .views import (AlmacenListView, HijoDeleteView, HijoUpdateView,
                    PersonaAlimentosDeleteView, PersonaAlimentosUpdateView,
                    PersonaCreateView, PersonaDeleteView, PersonaDetailView,
                    PersonaListView, PersonaUpdateView)

app_name = "adra"
# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r"personas", views.PersonaViewSet)
router.register(r"almacen", views.AlmacenViewSet)
router.register(r"users", views.UserViewSet)

urlpatterns = [
    path("api/", include((router.urls, "api"), namespace="api")),
    path(
        "api/token/",
        jwt_views.TokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    # personas url
    path("", PersonaListView.as_view(), name="persona-home"),
    path(
        "persona/<int:pk>/",
        PersonaDetailView.as_view(),
        name="personas_detail",
    ),
    path("persona/new/", PersonaCreateView.as_view(), name="persona-create"),
    path(
        "persona/<int:pk>/update/",
        PersonaUpdateView.as_view(),
        name="persona-update",
    ),
    path(
        "persona/<int:pk>/delete/",
        PersonaDeleteView.as_view(),
        name="persona-delete",
    ),
    # end persona url
    # almacen url
    path("almacen/", AlmacenListView.as_view(), name="almacen-home"),
    path("almacen/<int:pk>/update/", views.AlmacenUpdateView.as_view(), name="almacen-update"),
    # end almacen url
    # statistics
    path("statistics/", views.statistics_persona, name="statistics-personas"),
    path("telegram/", views.telegram_messages, name="telegram_message_view"),
    path("export/csv/", views.export_users_csv, name="exportar-users-csv"),
    path("export/pdf/<int:pk><str:mode>", views.generar_hoja_entrega, name="pdf_form"),
    path("export/hoja-entrega-global", views.generar_hoja_entrega_global, name="hoja_entrega_global"),
    path("export/valoracion-social", views.valoracion_social_global, name="valoracion_social"),
    path(
        "export/docx/<int:pk>",
        views.generar_hoja_valoracion_social,
        name="docx_form",
    ),
    # end statistics
    # buscar url
    path("buscar/", views.buscar, name="buscar"),
    path("buscar-alimentos-por-fecha/", views.buscar_fecha, name="buscar-por-fecha"),
    # end bucar url
    # alimentos url
    path(
        "persona/<int:pk>/alimentos",
        views.adauga_alimentos_persona,
        name="alimentos-create",
    ),
    path(
        "persona/alimentos/<int:pk>/update",
        PersonaAlimentosUpdateView.as_view(),
        name="persona-update-alimentos",
    ),
    path(
        "persona/alimentos/<int:pk>/delete",
        PersonaAlimentosDeleteView.as_view(),
        name="persona-alimentos-delete",
    ),
    # end alimentos url
    # hijos url
    path(
        "persona/<int:pk>/hijos", views.anadir_familiar, name="hijo-create"
    ),
    path(
        "persona/hijos/<int:pk>/update",
        HijoUpdateView.as_view(),
        name="hijo-update",
    ),
    path(
        "persona/hijos/<int:pk>/delete",
        HijoDeleteView.as_view(),
        name="hijo-delete",
    ),
    # end hijos url
    path("edit/", views.edit, name="edit-profile"),
    path("get-data/", views.get_data, name="get_data"),
    # path(
    #     "get-beneficiarios-activos/<int:number>",
    #     views.get_beneficiarios_activos,
    #     name="get_beneficiarios_activos",
    # ),
    path("configuracion/", views.configuracion, name="configuracion"),
    path("generar_recuento_file/", views.generar_recuento_beneficiaros, name="recuento_beneficiarios"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

adra/views.py
import glob
import io
import os
import subprocess  # imported for using queue.Empty exception
from datetime import datetime
from multiprocessing import Process
from pathlib import Path

import telegram
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.storage import FileSystemStorage
from django.db import connection
from django.db.models import Q, Sum
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page, never_cache
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_tenants.utils import get_tenant_model
from docx import Document
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, PatternFill
from PyPDF2 import PdfFileMerger, PdfFileReader, PdfFileWriter
from rest_framework import permissions, viewsets
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from adra.utils.adra_util import (
    AdraUtils,
    AgeCalculacion,
    DeliverySheet,
    RecuntoBeneficiarios,
    UploadExcelUsers,
    ValoracionSocial,
)
from delegaciones.models import BeneficiariosGlobales, Delegaciones

from .filters import AlimentosFilters
from .forms import (
    AlimentosFrom,
    AlimentosRepatrirForm,
    AlmacenAlimentosFrom,
    DelegacionForm,
    HijoForm,
    PersonaForm,
    ProfileEditForm,
    UserEditForm,
)
from .models import (
    Alimentos,
    AlimentosRepatir,
    AlmacenAlimentos,
    Hijo,
    Persona,
)
from .serializers import (
    AlacenAlimentosSerializer,
    PersonaSerializer,
    UserSerializer,
)


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES,
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request, "El perfil se ha actualizado correctamente"
            )
            return redirect("adra:edit-profile")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(
        request,
        "account/edit-perfile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


class PersonaListView(LoginRequiredMixin, ListView):
    template_name = "adra/index.html"
    context_object_name = "beneficiarios"
    model = Persona
    login_url = "account_login"
    paginate_by = 12
    queryset = Persona.objects.filter(active=True).exclude(covid=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # enviar al misma pagina varios contextos
        context["hijo"] = Hijo.objects
        context["hijomenor"] = Hijo
        context["nbar"] = "home"
        context["debug"] = settings.DEBUG
        context["platform_name"] = settings.PLATFORM_NAME

        return context


# ir a la pagina detallada de cada persona
class PersonaDetailView(LoginRequiredMixin, DetailView):
    model = Persona
    template_name = "adra/detail.html"
    context_object_name = "persona"
    login_url = "account_login"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = AlimentosFilters(
            self.request.GET, queryset=self.get_queryset()
        )
        return context


class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    success_url = "/"
    form_class = PersonaForm

    def form_valid(self, form):
        # print(form)
        # print(form.cleaned_data)
        logic = Q(
            documentacion_beneficiario=form.cleaned_data["dni"]
            if form.cleaned_data["dni"]
            else form.cleaned_data["otros_documentos"],
            telefono=form.cleaned_data["telefono"],
            # nombre_beneficiario=form.cleaned_data["nombre_apellido"],
            _connector=Q.OR,
        )
        beneficario_global = BeneficiariosGlobales.objects.filter(
            logic, nombre_beneficiario=form.cleaned_data["nombre_apellido"]
        )
        # print(beneficario_global)
        # print(beneficario_global.count())

        if beneficario_global.count() > 0:
            for beneficario in beneficario_global:
                # print(beneficario.delegacion_name)

                messages.warning(
                    self.request,
                    "{} es beneficiario de la oar {} desde {}".format(
                        beneficario.nombre_beneficiario,
                        beneficario.delegacion_name,
                        beneficario.created_at.strftime("%d %B, %Y"),
                    ),
                )
            return super().form_invalid(form)
        else:
            form.instance.modificado_por = self.request.user
            messages.add_message(
                self.request,
                messages.SUCCESS,
                "Beneficiario añadido con exito!",
            )
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nbar"] = "create"

        try:
            p = Persona.objects.latest("created_at")
            context["bas"] = p
        except Persona.DoesNotExist:
            context["bas"] = None

        return context


class PersonaUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Persona
    form_class = PersonaForm

    success_message = "Beneficiario actualizado satisfactoriamente!!"

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["up"] = "update"
        return context


class PersonaDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Persona
    success_message = "Beneficirio borrado corectamente"
    success_url = "/"


def adauga_alimentos_persona(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    almacen = AlmacenAlimentos.objects.all().first()

    if request.method == "POST":
        print(request.POST)
        a_form = AlimentosFrom(request.POST)
        if a_form.is_valid():
            alimentos = a_form.save(commit=False)

            almacen.alimento_1 -= alimentos.alimento_1
            almacen.alimento_2 -= alimentos.alimento_2
            almacen.alimento_3 -= alimentos.alimento_3
            almacen.alimento_4 -= alimentos.alimento_4
            almacen.alimento_5 -= alimentos.alimento_5
            almacen.alimento_6 -= alimentos.alimento_6
            almacen.alimento_7 -= alimentos.alimento_7
            almacen.alimento_8 -= alimentos.alimento_8
            almacen.alimento_9 -= alimentos.alimento_9
            almacen.alimento_10 -= alimentos.alimento_10
            almacen.alimento_11 -= alimentos.alimento_11
            almacen.alimento_12 -= alimentos.alimento_12
            almacen.alimento_13 -= alimentos.alimento_13
            almacen.alimento_14 -= alimentos.alimento_14
            almacen.alimento_15 -= alimentos.alimento_15
            almacen.alimento_16 -= alimentos.alimento_16

            alimentos.persona = persona
            alimentos.modificado_por = request.user
            almacen.save()
            alimentos.save()
            messages.success(
                request, "Los alimentos se han entregado correctamente!"
            )
            return redirect(persona)

    else:
        alm_repatir = AlimentosRepatir.objects.all().first()

        init_reparto_alimento = {}
        for index in range(1, 17):
            if getattr(alm_repatir, f"alimento_{index}_type") == "unidad":
                babys = len(
                    [fam for fam in persona.hijo.all() if fam.age <= 3]
                )
                if babys > 0 and index in [12, 13]:
                    init_reparto_alimento[f"alimento_{index}"] = (
                        getattr(alm_repatir, f"alimento_{index}") * babys
                    )
                    continue
                else:
                    if index in [12, 13]:
                        init_reparto_alimento[f"alimento_{index}"] = 0
                        continue
                init_reparto_alimento[f"alimento_{index}"] = (
                    getattr(alm_repatir, f"alimento_{index}")
                    * persona.numero_beneficiarios
                )
            else:
                if 0 <= persona.numero_beneficiarios <= 3:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_0_3"
                    )
                elif 4 <= persona.numero_beneficiarios <= 6:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_4_6"
                    )
                elif 7 <= persona.numero_beneficiarios <= 10:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_7_9"
                    )
                else:

adra/templates/statistics/index.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}


{% block title %}
Adra-Statistics
{% endblock %}

{% block content %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col"></th>
            <th scope="col">0 a 2</th>
            <th scope="col">3 a 15</th>
            <th scope="col">16-64</th>
            <th scope="col">+ de 65</th>
            <th scope="col">Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Mujeres</th>
            <td>{{ total_per_mujer_02 }}</td>
            <td>{{ total_per_mujer_03 }}</td>
            <td>{{ total_per_mujer_16 }}</td>
            <td>{{ total_per_mujer_65 }}</td>
            <td>{{ total_mujeres }}</td>
        </tr>
        <tr>
            <th scope="row">Hombres</th>
            <td>{{ total_per_hombre_02 }}</td>
            <td>{{ total_per_hombre_03 }}</td>
            <td>{{ total_per_hombre_16 }}</td>
            <td>{{ total_per_hombre_65 }}</td>
            <td>{{ total_hombres }}</td>
        </tr>
        <tr>
            <th scope="row">Total</th>
            <td>{{ total_02 }}</td>
            <td>{{ total_03 }}</td>
            <td>{{ total_16 }}</td>
            <td>{{ total_65 }}</td>
            <td>{{ total_personas }}</td>
        </tr>
    </tbody>
</table>
<br>
<div class="row"  >
    <div class="col-md-4">
        <h5>Personas con Discapacidad</h5>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">Discapacidad</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">{{ discapacidad }}</th>

                </tr>

            </tbody>
        </table>
    </div>
    <div class="col-md-4">
        <h5>Beneficiarios</h5>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">Total Beneficiarios</th>
                    <th scope="col">Total Familiares</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">{{ total_beneficiarios }}</th>
                    <th scope="row">{{ total_familiares }}</th>

                </tr>

            </tbody>
        </table>
    </div>
    <div class="col-md-4" style="display: flex;justify-content: center;align-items: center;">

        
        <a role="button" class="btn btn-success active" href="{% url 'adra:recuento_beneficiarios' %}" style="display: flex;justify-content: center;align-items: center;">
            <i class="large material-icons" style="font-size: 36px;color: white">file_download</i>
            Generar Recuento Beneficiarios
        </a>
    </div>
</div>
<!-- 
    <div class="col col-md-6" style="height: 25vh;min-height: 25vh;position:relative;">
        <h3 class="text-left pt-5">Usuarios activos por busqueda</h3>
        <p><b>introduce el numero de entregas</b></p>
        <div id="app-activos">
            <div class="input-group col-sm-6 d-flex justify-content-center align-items-center text-black-50"
                 style="padding-left: 0;margin-top: 2vh;">
                <input type="number" v-model="number_search" class="form-control" min="1" id="active_ben">
                <label for="active_ben"></label>
            </div>
            <h4 style="margin-top: 1vh">Beneficiarios activos: <span
                    style="font-size: 20px;color: red;margin-left: 2%;">{beneficiarios} </span></h4>
        </div>
    </div> -->

<div class="row">
    <div class="col">
        <h1 class="text-center pt-5">Registros por años</h1>
        <div id="main" style="width:100%; height:400px;"></div>
    </div>
</div>

{% endblock content %}
{% block script %}
<script>

    // var app = new Vue({
    //     el: '#app-activos',
    //     delimiters: ['{', '}'],
    //     data: {
    //         number_search: 1,
    //         beneficiarios: ''
    //     },
    //     watch: {
    //         number_search: function (old) {
    //             this.get_data()

    //         }
    //     },
    //     mounted() {
    //         this.get_data()
    //     },
    //     methods: {
    //         get_data: function () {
    //             let vm = this;
    //             if (vm.number_search) {
    //                 axios.get(`/get-beneficiarios-activos/${this.number_search}`)
    //                     .then(function (response) {
    //                         vm.beneficiarios = response.data.num

    //                     })
    //                     .catch(function (error) {
    //                         console.log(error);
    //                     })
    //             }

    //         }
    //     }
    // })


    // based on prepared DOM, initialize echarts instance
    var myChart = echarts.init(document.getElementById('main'));


    let option = {
        tooltip: {
            trigger: 'item',
            formatter: '{c} registros'
        },
        xAxis: {
            type: 'category',
            data: ['2018', '2019', '2020', '2021']
        },
        yAxis: {
            type: 'value'
        },
    };


    axios.get("{% url 'adra:get_data' %}")
        .then(function (response) {
            console.log(response);

            myChart.setOption({
                xAxis: {
                    type: 'category',
                    data: response.data.years
                },
                series: [{
                    data: response.data.reg,
                    type: 'line'
                }]
            });
        })
        .catch(function (error) {
            console.log(error);
        })


    // use configuration item and data specified to show chart
    myChart.setOption(option);
    window.onresize = function () {
        myChart.resize();
    };
</script>

{% endblock %}