adra/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt import views as jwt_views

from . import views
from .views import (AlmacenListView, HijoDeleteView, HijoUpdateView,
                    PersonaAlimentosDeleteView, PersonaAlimentosUpdateView,
                    PersonaCreateView, PersonaDeleteView, PersonaDetailView,
                    PersonaListView, PersonaUpdateView)

app_name = "adra"
# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r"personas", views.PersonaViewSet)
router.register(r"almacen", views.AlmacenViewSet)
router.register(r"users", views.UserViewSet)

urlpatterns = [
    path("api/", include((router.urls, "api"), namespace="api")),
    path(
        "api/token/",
        jwt_views.TokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    # personas url
    path("", PersonaListView.as_view(), name="persona-home"),
    path(
        "persona/<int:pk>/",
        PersonaDetailView.as_view(),
        name="personas_detail",
    ),
    path("persona/new/", PersonaCreateView.as_view(), name="persona-create"),
    path(
        "persona/<int:pk>/update/",
        PersonaUpdateView.as_view(),
        name="persona-update",
    ),
    path(
        "persona/<int:pk>/delete/",
        PersonaDeleteView.as_view(),
        name="persona-delete",
    ),
    # end persona url
    # almacen url
    path("almacen/", AlmacenListView.as_view(), name="almacen-home"),
    path("almacen/<int:pk>/update/", views.AlmacenUpdateView.as_view(), name="almacen-update"),
    # end almacen url
    # statistics
    path("statistics/", views.statistics_persona, name="statistics-personas"),
    path("telegram/", views.telegram_messages, name="telegram_message_view"),
    path("export/csv/", views.export_users_csv, name="exportar-users-csv"),
    path("export/pdf/<int:pk><str:mode>", views.generar_hoja_entrega, name="pdf_form"),
    path("export/hoja-entrega-global", views.generar_hoja_entrega_global, name="hoja_entrega_global"),
    path("export/valoracion-social", views.valoracion_social_global, name="valoracion_social"),
    path(
        "export/docx/<int:pk>",
        views.generar_hoja_valoracion_social,
        name="docx_form",
    ),
    # end statistics
    # buscar url
    path("buscar/", views.buscar, name="buscar"),
    path("buscar-alimentos-por-fecha/", views.buscar_fecha, name="buscar-por-fecha"),
    # end bucar url
    # alimentos url
    path(
        "persona/<int:pk>/alimentos",
        views.adauga_alimentos_persona,
        name="alimentos-create",
    ),
    path(
        "persona/alimentos/<int:pk>/update",
        PersonaAlimentosUpdateView.as_view(),
        name="persona-update-alimentos",
    ),
    path(
        "persona/alimentos/<int:pk>/delete",
        PersonaAlimentosDeleteView.as_view(),
        name="persona-alimentos-delete",
    ),
    # end alimentos url
    # hijos url
    path(
        "persona/<int:pk>/hijos", views.anadir_familiar, name="hijo-create"
    ),
    path(
        "persona/hijos/<int:pk>/update",
        HijoUpdateView.as_view(),
        name="hijo-update",
    ),
    path(
        "persona/hijos/<int:pk>/delete",
        HijoDeleteView.as_view(),
        name="hijo-delete",
    ),
    # end hijos url
    path("edit/", views.edit, name="edit-profile"),
    path("get-data/", views.get_data, name="get_data"),
    # path(
    #     "get-beneficiarios-activos/<int:number>",
    #     views.get_beneficiarios_activos,
    #     name="get_beneficiarios_activos",
    # ),
    path("configuracion/", views.configuracion, name="configuracion"),
    path("generar_recuento_file/", views.generar_recuento_beneficiaros, name="recuento_beneficiarios"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

adra/views.py
import glob
import io
import os
import subprocess  # imported for using queue.Empty exception
from datetime import datetime
from multiprocessing import Process
from pathlib import Path

import telegram
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.storage import FileSystemStorage
from django.db import connection
from django.db.models import Q, Sum
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page, never_cache
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django_tenants.utils import get_tenant_model
from docx import Document
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, PatternFill
from PyPDF2 import PdfFileMerger, PdfFileReader, PdfFileWriter
from rest_framework import permissions, viewsets
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from adra.utils.adra_util import (
    AdraUtils,
    AgeCalculacion,
    DeliverySheet,
    RecuntoBeneficiarios,
    UploadExcelUsers,
    ValoracionSocial,
)
from delegaciones.models import BeneficiariosGlobales, Delegaciones

from .filters import AlimentosFilters
from .forms import (
    AlimentosFrom,
    AlimentosRepatrirForm,
    AlmacenAlimentosFrom,
    DelegacionForm,
    HijoForm,
    PersonaForm,
    ProfileEditForm,
    UserEditForm,
)
from .models import (
    Alimentos,
    AlimentosRepatir,
    AlmacenAlimentos,
    Hijo,
    Persona,
)
from .serializers import (
    AlacenAlimentosSerializer,
    PersonaSerializer,
    UserSerializer,
)


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES,
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request, "El perfil se ha actualizado correctamente"
            )
            return redirect("adra:edit-profile")
        else:
            messages.error(request, "Error updating your profile")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(
        request,
        "account/edit-perfile.html",
        {"user_form": user_form, "profile_form": profile_form},
    )


class PersonaListView(LoginRequiredMixin, ListView):
    template_name = "adra/index.html"
    context_object_name = "beneficiarios"
    model = Persona
    login_url = "account_login"
    paginate_by = 12
    queryset = Persona.objects.filter(active=True).exclude(covid=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # enviar al misma pagina varios contextos
        context["hijo"] = Hijo.objects
        context["hijomenor"] = Hijo
        context["nbar"] = "home"
        context["debug"] = settings.DEBUG
        context["platform_name"] = settings.PLATFORM_NAME

        return context


# ir a la pagina detallada de cada persona
class PersonaDetailView(LoginRequiredMixin, DetailView):
    model = Persona
    template_name = "adra/detail.html"
    context_object_name = "persona"
    login_url = "account_login"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = AlimentosFilters(
            self.request.GET, queryset=self.get_queryset()
        )
        return context


class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    success_url = "/"
    form_class = PersonaForm

    def form_valid(self, form):
        # print(form)
        # print(form.cleaned_data)
        logic = Q(
            documentacion_beneficiario=form.cleaned_data["dni"]
            if form.cleaned_data["dni"]
            else form.cleaned_data["otros_documentos"],
            telefono=form.cleaned_data["telefono"],
            # nombre_beneficiario=form.cleaned_data["nombre_apellido"],
            _connector=Q.OR,
        )
        beneficario_global = BeneficiariosGlobales.objects.filter(
            logic, nombre_beneficiario=form.cleaned_data["nombre_apellido"]
        )
        # print(beneficario_global)
        # print(beneficario_global.count())

        if beneficario_global.count() > 0:
            for beneficario in beneficario_global:
                # print(beneficario.delegacion_name)

                messages.warning(
                    self.request,
                    "{} es beneficiario de la oar {} desde {}".format(
                        beneficario.nombre_beneficiario,
                        beneficario.delegacion_name,
                        beneficario.created_at.strftime("%d %B, %Y"),
                    ),
                )
            return super().form_invalid(form)
        else:
            form.instance.modificado_por = self.request.user
            messages.add_message(
                self.request,
                messages.SUCCESS,
                "Beneficiario añadido con exito!",
            )
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nbar"] = "create"

        try:
            p = Persona.objects.latest("created_at")
            context["bas"] = p
        except Persona.DoesNotExist:
            context["bas"] = None

        return context


class PersonaUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Persona
    form_class = PersonaForm

    success_message = "Beneficiario actualizado satisfactoriamente!!"

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["up"] = "update"
        return context


class PersonaDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Persona
    success_message = "Beneficirio borrado corectamente"
    success_url = "/"


def adauga_alimentos_persona(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    almacen = AlmacenAlimentos.objects.all().first()

    if request.method == "POST":
        print(request.POST)
        a_form = AlimentosFrom(request.POST)
        if a_form.is_valid():
            alimentos = a_form.save(commit=False)

            almacen.alimento_1 -= alimentos.alimento_1
            almacen.alimento_2 -= alimentos.alimento_2
            almacen.alimento_3 -= alimentos.alimento_3
            almacen.alimento_4 -= alimentos.alimento_4
            almacen.alimento_5 -= alimentos.alimento_5
            almacen.alimento_6 -= alimentos.alimento_6
            almacen.alimento_7 -= alimentos.alimento_7
            almacen.alimento_8 -= alimentos.alimento_8
            almacen.alimento_9 -= alimentos.alimento_9
            almacen.alimento_10 -= alimentos.alimento_10
            almacen.alimento_11 -= alimentos.alimento_11
            almacen.alimento_12 -= alimentos.alimento_12
            almacen.alimento_13 -= alimentos.alimento_13
            almacen.alimento_14 -= alimentos.alimento_14
            almacen.alimento_15 -= alimentos.alimento_15
            almacen.alimento_16 -= alimentos.alimento_16

            alimentos.persona = persona
            alimentos.modificado_por = request.user
            almacen.save()
            alimentos.save()
            messages.success(
                request, "Los alimentos se han entregado correctamente!"
            )
            return redirect(persona)

    else:
        alm_repatir = AlimentosRepatir.objects.all().first()

        init_reparto_alimento = {}
        for index in range(1, 17):
            if getattr(alm_repatir, f"alimento_{index}_type") == "unidad":
                babys = len(
                    [fam for fam in persona.hijo.all() if fam.age <= 3]
                )
                if babys > 0 and index in [12, 13]:
                    init_reparto_alimento[f"alimento_{index}"] = (
                        getattr(alm_repatir, f"alimento_{index}") * babys
                    )
                    continue
                else:
                    if index in [12, 13]:
                        init_reparto_alimento[f"alimento_{index}"] = 0
                        continue
                init_reparto_alimento[f"alimento_{index}"] = (
                    getattr(alm_repatir, f"alimento_{index}")
                    * persona.numero_beneficiarios
                )
            else:
                if 0 <= persona.numero_beneficiarios <= 3:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_0_3"
                    )
                elif 4 <= persona.numero_beneficiarios <= 6:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_4_6"
                    )
                elif 7 <= persona.numero_beneficiarios <= 10:
                    init_reparto_alimento[f"alimento_{index}"] = getattr(
                        alm_repatir, f"alimento_{index}_7_9"
                    )
                else:

adra/templates/adra/alimentos_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}
        <div class="col-md-8">
            <h1>Personas</h1>
            <form method="POST">
                {% csrf_token %}
                <h1>Chiar vrei sa stergi la entrega con fecha de "{{ object.created_at|date:"Y-m-d" }}" ?</h1>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Sterge</button>
                    <a href=" {% url 'adra:persona-home' %}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    {% endblock %}
</div>

adra/templates/adra/anuncio.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Telegram</title>
  </head>
  <body>
    <div class="container">
        <h1 style="color: red;margin-top: 5%;">Adra Torrejon Informa</h1>
        <p style="font-size: 18px;"><b>A partir de ahora ya no vamos a enviar mensajes</b>  </p>
        <p><b>La via de comunicación sera a traves de <span class="text-danger" style="font-size: 24px;"> telegram</span> que os paso el enlace para descargar</b></p>
        <p><b> <a href="https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=es">Android</a></b></p>
        <p><b> <a href="https://apps.apple.com/es/app/telegram-messenger/id686449807">Iphone</a></b></p>
        <p><b>Una vez instalada ,teneis que pulsar este enlace de abajo y uniros al chat que he creado para hablar con vosotros,es urgente</b></p>
        <p><b><a href="https://t.me/joinchat/AAAAAFXCpY63-5afLQbkcA">Chat Adra</a></b></p>
    </div>
  </body>
</html>

adra/templates/adra/dashboard.html
<!-- {% extends "_base.html" %} -->
{% load static %}
{% load verbose_names %}
{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hola,
            {% if user.last_name %}
            {{ user.last_name | capfirst }}
            {% else %}
            {{ user.username | capfirst }}
            {% endif %}!</h1>
        <h4>Esta plataforma es la forma más eficaz de gestionar los beneficiarios, gestionar los documentos asociados a
            ellos, recordatorios de las caducidades de alimentos  etc... esperamos que la disfruté .</h4>
      
    </div>
</div>

<div class="row">
    <div class="col-md-6 center-all-c text-justify" style="justify-content: space-evenly; align-items:start; height: 20.5vh;">
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Total beneficiarios</th>
                <th scope="col">Beneficiarios añadidos en <span class="text-secondary">{{currentYear}}</span>  </th>
                <th scope="col">Entregas hasta ahora </th>
              </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center">{{ total_personas}}</td>
                    <td class="text-center">{{ beneficiars_year }}</td>
                    <td class="text-center">{{ current_entregas }}</td>
                </tr>
                <!-- {% for beneficiario in last_five_benefiarios %}
                    <tr>
                    
                    <td> 
                        <a href="{% url 'adra:personas_detail' beneficiario.id %}" class="mr-2">{{beneficiario.nombre_apellido}}</a>
                    </td>
                    <td>{{beneficiario.numero_adra}}</td>
                    <td>{{beneficiario.created_at |timesince}}</td>
                  </tr>
                
                {% endfor %}
               -->
               
            </tbody>
          </table>
       
       
        <!-- <div class="  center-all-r">
            <h2>Total beneficiarios <sup class="badge badge-info">{{ total_personas}}</sup></h2>
        </div>
        <div class="  center-all-r">
            <h2>Beneficiarios añadidos en <span class="text-secondary">{{currentYear}}</span>  <sup class="badge badge-info">{{ beneficiars_year }}</sup></h2>
        </div>
        <div class="  center-all-r">
            <h2>Entregas hasta ahora <sup class="badge badge-info">{{ current_entregas }}</sup></h2>
        </div>
        <div class="   mb-3 center-all-r">
            <p><a class="btn btn-outline-dark " href="{% url 'adra:statistics-personas' %}" role="button">Mas  info »</a></p>
        </div> -->
    </div>
    <div class="col-md-6">
        <h2 class="center-all-r mb-3">Ultimos Beneficiarios añadidos</h2>
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Numero beneficario</th>
                <th scope="col">Hace</th>
              </tr>
            </thead>
            <tbody>
                {% for beneficiario in last_five_benefiarios %}
                    <tr>
                    
                    <td> 
                        <a href="{% url 'adra:personas_detail' beneficiario.id %}" class="mr-2">{{beneficiario.nombre_apellido}}</a>
                    </td>
                    <td>{{beneficiario.numero_adra}}</td>
                    <td>{{beneficiario.created_at |timesince}}</td>
                  </tr>
                
                {% endfor %}
              
               
            </tbody>
          </table>
    </div>
  
</div>
<hr>

{% comment %} 
<div class="row">
    <div class="col-md-6">
        <h2 class="center-all-r mb-3">Ultimos Beneficiarios añadidos</h2>
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Numero beneficario</th>
                <th scope="col">Hace</th>
              </tr>
            </thead>
            <tbody>
                {% for beneficiario in last_five_benefiarios %}
                    <tr>
                    
                    <td> 
                        <a href="{% url 'adra:personas_detail' beneficiario.id %}" class="mr-2">{{beneficiario.nombre_apellido}}</a>
                    </td>
                    <td>{{beneficiario.numero_adra}}</td>
                    <td>{{beneficiario.created_at |timesince}}</td>
                  </tr>
                
                {% endfor %}
              
               
            </tbody>
          </table>
          
         
    </div>
    <div class="col-md-6">

    </div>
</div> {% endcomment %}

{% endblock %}

adra/templates/adra/hijo_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
    {% block content %}
        <div class="col-md-8">
            <h1>FAMILIAR</h1>
            <form method="POST">
                {% csrf_token %}
                <h1>Quieres borrar el familiar "{{ object.nombre_apellido }}" ?</h1>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Borrrar</button>
                    <a href=" {% url 'adra:persona-home' %}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    {% endblock %}
</div>

adra/templates/adra/hijo_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
<div class="row">
  {% block content %}

  <div class="col-md-12 p-3" style="box-shadow: 0px 0px 23px -2px rgba(186,186,186,1);">
    {# <h1>Añadir Familiar</h1> #}
    {% if up == 'update' %}
    <h1 class="pb-3 text-center">Modificar datos Familiar</h1>
    {% else %}
    <h1 class="pb-3 text-center">Añadir Familiar</h1>
    {% endif %}
    <form method="POST">
      {% csrf_token %}

      <div class="form-row">
        <div class="form-group col-md-4 mb-0">
          {{ form.parentesco|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.nombre_apellido|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.dni|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.otros_documentos|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.fecha_nacimiento|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
          {{ form.sexo|as_crispy_field }}
        </div>


      </div>
      <div class="form-row">

        <div class="form-group col-md-4 mb-0">
          <div class="form-check">
            {{ form.discapacidad|as_crispy_field }}
          </div>
        </div>

      </div>

      <!-- {{ form|crispy }} -->

      <div class="form-group">
        <button class="btn btn-info btn-block" type="submit">
          {% if up == 'update' %}
          <span class="pb-3 text-center">Modificar</span>
          {% else %}
          <span class="pb-3 text-center">Añadir</span>
          {% endif %}

        </button>
      </div>
    </form>
  </div>

  {% endblock %}
</div>

adra/templates/adra/index.html
<!-- {% extends "_base.html" %} -->
{% load static %}
{% load verbose_names %}
{% block content %}

    {% if beneficiarios %}

        <div class="row">
            {% for beneficiario in beneficiarios %}
                <div class="col-md-6 col-lg-3">
                    <div class="card wow fadeIn" data-wow-duration="2s"
                         style="box-shadow: 0px 0px 23px -2px rgba(186,186,186,1);">
                        <div class="card-body">
                            <div class="mx-auto d-block text-center">

                                {% if  beneficiario.sexo == 'hombre' %}
                                    <img class="rounded-circle mx-auto d-block"
                                         src="{% static 'images/chico.png' %}"
                                         alt="Card image cap" width="70" height="70">
                                {% else %}
                                    <img class="rounded-circle mx-auto d-block"
                                         src="{% static 'images/girl.png' %}"
                                         alt="Card image cap" width="70" height="70">
                                {% endif %}





                                <h5 class="text-sm-center mt-2 mb-1 text-truncate">{{ beneficiario.nombre_apellido }}</h5>
                                <div class="location text-sm-center">{{ beneficiario.numero_adra }}</div>
                                <div class="card-text text-sm-center">
                                    {% if  beneficiario.are_acte %}
                                        <i class="large material-icons"
                                           style="color:green;font-size: 34px;">verified_user</i>
                                    {% else %}
                                        <i class="large material-icons"
                                           style="color:red;font-size: 34px;">verified_user</i>
                                    {% endif %}
                                    {% if  beneficiario.discapacidad %}
                                        <i class="large material-icons"
                                           style="font-size: 34px;">accessible</i>
                                    {% endif %}
                                    {% if beneficiario.covid %}
                                        <i class="large material-icons" title="covid "
                                           style="font-size: 34px;color: #370617">grain</i>
                                    {% endif %}

                                    {% if beneficiario.get_babys_number > 0 %}
                                        <div style="display: inline-block !important;">
                                            <div style="display:flex;justify-content: center;align-items: center+">
                                                <i class="large material-icons" title="covid "
                                                   style="font-size: 34px;color: #168ae2">child_friendly</i> <span
                                                    style="margin-left: 2px;"> x {{ beneficiario.get_babys_number }}</span>
                                            </div>
                                        </div>
                                    {% endif %}


                                </div>
                            </div>
                            <p class="card-text text-center p-2" style="box-shadow: inset 1px 0px 6px 0px #00000014;
    border-radius: 13px; margin: 10px;">
                                Total: {{ beneficiario.numero_beneficiarios }}
                                {% if  beneficiario.numero_beneficiarios == 1 %}
                                    familiar
                                {% else %}
                                    familiares
                                {% endif %}
                            </p>
                            <div class="card-text text-center">
                                <a href="{% url 'adra:personas_detail' beneficiario.id %}" class="mr-2">
                                    <i class="large material-icons"
                                       style="font-size: 34px;color: darkslategrey">remove_red_eye</i>
                                </a>
                                <a href="{% url 'adra:persona-update' beneficiario.id %}" class="mr-2">
                                    <i class="large material-icons" style="font-size: 34px;">settings</i>

                                </a>
                                {% if user.is_staff %}
                                    <a href="{% url 'adra:persona-delete' beneficiario.id %}">
                                        <i class="large material-icons"
                                           style="font-size: 34px; color: red">delete</i>
                                    </a>

                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer">
                            <strong class="card-title mb-3">

                                {% if beneficiario.alimentos.all %}
                                    <p class="text-center" style="color: #484848">Recogido:
                                        {% for al in beneficiario.alimentos.all %}
                                            {% if forloop.first %}
                                                <span>{{ al.fecha_recogida|date:"d-m-Y" }}</span>
                                                <br>
                                                <span>{{ al.fecha_recogida|timesince }}</span>

                                            {% endif %}
                                        {% endfor %}
                                    </p>
                                {% else %}
                                    <p class=" text-center text-danger">Sin entrega</p>
                                {% endif %}


                            </strong>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>




        {% if is_paginated %}

            <div class="pagination" style="display: flex;justify-content: center">
              <span class="step-links " style="display:flex;">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" style="margin-right: 20px;"><i
                            class=" large material-icons ">chevron_left</i> </a>
                {% endif %}
                  <span class="current">
                  Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}" style="margin-left: 20px;">  <i
                              class=" large material-icons ">chevron_right</i></a>
                  {% endif %}
              </span>
            </div>


        {% endif %}


    {% else %}
        <p>No hay personas!!!</p>
    {% endif %}


{% endblock %}

adra/templates/adra/no_beneficiarios.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-12">
        <h3 class="lead"><span class="text-danger  ">El beneficiario no existe </span>, quizas esta en esta lista de
            usuarios que ya no estan activos en nuestra plataforma </h3>
        <table class="table mt-4 table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Numero adra</th>
                <th scope="col">Nombre</th>
                <th scope="col">Dni</th>
            </tr>
            </thead>
            <tbody>

            {% for b in ben %}
                <tr>
                    <th scope="row">{{ b.numero_adra }}</th>
                    {% if user.is_staff %}
                        <td><a href="{% url 'adra:persona-update' b.id %}" class="mr-2">{{ b.nombre_apellido }}</a></td>
                    {% else %}
                        <td>{{ b.nombre_apellido }}</td>
                    {% endif %}
                    <td>{{ b.dni }}</td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

    </div>
{% endblock %}